# This is AEXO Application YML
# Update your config here


# Blog Variables
blog:
  name: 'AEXO'
  # Avator Relative URL, example: assets/images/avator.png
  avator: 'assets/images/avator.png'
  author: 'Author'
  description: 'Description'
  externalLinks:
    -
      label: 'Social'
      links:
        -
          url: 'https://github.com/aquariuslt'
          displayName: 'Github'
          description: 'Github'

    -
      label: 'Friend Links'
      links:
        -
          displayName: 'Aquariuslt Blog'
          url: 'https://blog.aquariuslt.com'
          description: ''



  # Hidden Category Lists
  categories:
    filter: true
    hidden:
      - 'Secret'

  tags:
    filter: true
    hidden:
      - 'Secret'

  # Enable About Page
  about:
    enable: true


  # Disqus Config
  # Replace your disqus config here.
  disqus:
    enable: true
    shortName: 'disqus'

  # Progressive Web App
  pwa:
    enable: true
    name: 'Your AEXO app name'
    shortName: 'Blog'
    description: 'Your AEXO app description'
    icon: 'app-icon.png'
    developer:
      name: 'Aquariuslt'
      url: 'https://github.com/aquariuslt'

# Blog Deploy Options
# Domain
# cname: 'blog.yoursite.com'

# Deploy
# Replace with your github.io repository url here
deploy:
  repo: 'https://github.com/xxxx/xxxx.github.io.git'
  remote: 'origin'
  branch: 'master'
  cacheDir: '.cache'
  clone: '.cache'
